/**
 * File Upload Utilities
 * Validation and helper functions for file uploads
 * 
 * Generated by AGL
 */

export interface ValidationOptions {
  allowedTypes?: string[];
  maxSizeMB?: number;
}

/**
 * Validate a file before upload
 * @throws Error if validation fails
 */
export function validateFile(
  file: File | Blob,
  options: ValidationOptions = {}
): void {
  const { allowedTypes, maxSizeMB } = options;

  // Check file size
  if (maxSizeMB && file.size > maxSizeMB * 1024 * 1024) {
    throw new Error(`File size exceeds ${maxSizeMB}MB limit`);
  }

  // Check file type
  if (allowedTypes && allowedTypes.length > 0) {
    const mimeType = (file as any).type || 'application/octet-stream';
    
    if (!matchesMimeType(mimeType, allowedTypes)) {
      throw new Error(
        `File type ${mimeType} not allowed. Allowed types: ${allowedTypes.join(', ')}`
      );
    }
  }
}

/**
 * Check if a MIME type matches any of the allowed patterns
 * Supports wildcards like 'image/*'
 */
function matchesMimeType(mimeType: string, patterns: string[]): boolean {
  return patterns.some(pattern => {
    if (pattern.endsWith('/*')) {
      const prefix = pattern.slice(0, -2);
      return mimeType.startsWith(prefix + '/');
    }
    return mimeType === pattern;
  });
}

/**
 * Get file extension from filename or MIME type
 */
export function getFileExtension(file: File | Blob): string {
  const fileName = (file as any).name;
  if (fileName) {
    const parts = fileName.split('.');
    if (parts.length > 1) {
      return parts[parts.length - 1];
    }
  }

  // Fallback to MIME type mapping
  const mimeType = (file as any).type || 'application/octet-stream';
  return getMimeTypeExtension(mimeType);
}

/**
 * Map MIME type to common file extension
 */
function getMimeTypeExtension(mimeType: string): string {
  const map: Record<string, string> = {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/gif': 'gif',
    'image/webp': 'webp',
    'video/mp4': 'mp4',
    'video/mpeg': 'mpeg',
    'video/webm': 'webm',
    'application/pdf': 'pdf',
    'application/json': 'json',
    'text/plain': 'txt',
  };

  return map[mimeType] || 'bin';
}
