/**
 * Controllers
 * Central exports for all backend controllers
 * 
 * Generated by AGL
 */

// videomanagement feature controllers
export * from './videomanagement';
// aiprocessing feature controllers
export * from './aiprocessing';
// statistics feature controllers
export * from './statistics';
// iotmonitoring feature controllers
export * from './iotmonitoring';
