/**
 * IoTMonitoringController * Business logic for iotmonitoring feature
 * 
 * Generated by AGL
 */

// Domain types from spec
import { DatabaseService } from '@/services/database.service';
import { mqttService } from '@/services/mqtt.service';
import type { IoTDevice } from '@repo/types';

function generateId(): string {
  return `${Date.now()}-${Math.floor(Math.random() * 100000)}`;
}

type AgentInfoPayload = {
  device_id: string;
  event: string;
  info: {
    hostname: string;
    version: {
      version: string;
      versionTs: number;
    };
  };
};
export class IoTMonitoringController {
  private db = DatabaseService.getInstance();
  
  /**
   * Controller methods for iotmonitoring feature
   */

  /**
   * listDevices   */
  async listDevices(): Promise<IoTDevice> {
    try {
      // TODO: Implement listDevices      // This method should:
      // 1. Validate input parameters
      // 2. Call appropriate services
      // 3. Transform and return data
      
      throw new Error('Not implemented');
    } catch (error) {
      console.error('Error in listDevices:', error);
      throw error;
    }
  }

  /**
   * refreshDeviceStatus   */
  async refreshDeviceStatus(deviceId: string): Promise<IoTDevice | null> {
    try {
      const agentInfo = await this.db.agentInfo.findUnique({
        where: { deviceId },
      });

      if (!agentInfo) {
        return null;
      }

      // Convert BigInt to Number for JSON serialization
      return {
        ...agentInfo
      };
    } catch (error) {
      console.error('Error in refreshDeviceStatus:', error);
      throw error;
    }
  }

  /**
   * Start record remotly
   */
  async startRecord(deviceId: string): Promise<{ ok : boolean; id?: string }> {
    try {
      const id = generateId();
      const payload = {
        type: 'start_record',
        data: {},
        id,
      };
      await mqttService.publish(`flashclip/${deviceId}/commands`, payload, {
        qos: 1,
      });

      return { ok: true, id };
    } catch (error) {
      console.error('Error in startRecord:', error);
      throw { ok: false };
    }
  }

  /**
   * Save Agent Info
   */
  async saveAgentInfo(
    deviceId: string,
    info: AgentInfoPayload
  ) {
    // Extract versionTimestamp and convert to BigInt if present
    let versionTimestamp = null;
    if (info?.info?.version?.versionTs) {
      versionTimestamp = BigInt(info.info.version.versionTs);
    }

    const agentInfo = await this.db.agentInfo.upsert({
      where: { deviceId },
      update: {
        info,
        versionTimestamp,
      },
      create: {
        deviceId,
        info,
        versionTimestamp,
      },
    });

    return agentInfo;
  };
}
