/**
 * AI Processing Service
 * Handles communication with the external AI processing endpoint
 * 
 * Generated by AGL
 */


interface VideoListResponse {
  success: boolean;
  data: Array<{
    videoId: string;
    timestamp: string;
    status: 'AVAILABLE' | 'PROCESSED' | 'PROCESSING' | 'FAILED';
    recommended: boolean;
    duration: number;
    thumbnailUrl: string;
  }>;
}

interface VideoDetailsResponse {
  success: boolean;
  data: {
    videoId: string;
    timestamp: string;
    status: 'AVAILABLE' | 'PROCESSED' | 'PROCESSING' | 'FAILED';
    recommended: boolean;
    duration: number;
    resolution: string;
    versions: Array<{
      type: 'ORIGINAL' | 'SUBTITLED' | 'SUBTITLED_ENGAGING' | 'SUBTITLED_EMOJI';
      url: string;
      title: string;
      description: string;
      thumbnailUrl: string;
    }>;
  };
}

interface ProcessVideoResponse {
  success: boolean;
  data: {
    jobId: string;
  };
}

interface JobStatusResponse {
  success: boolean;
  data: {
    jobId: string;
    status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
    progress: number;
    error?: string;
  };
}

export class AIProcessingService {
  private processingEndpoint: string;
  private deviceId: string;

  constructor() {
    this.processingEndpoint = process.env.PROCESSING_ENDPOINT || '';
    this.deviceId = process.env.DEVICE_ID || '';

    if (!this.processingEndpoint) {
      throw new Error('PROCESSING_ENDPOINT environment variable is not set');
    }

    if (!this.deviceId) {
      throw new Error('DEVICE_ID environment variable is not set');
    }
  }

  /**
   * List all videos for a device
   */
  async listVideos(): Promise<VideoListResponse> {
    const url = `${this.processingEndpoint}/devices/${this.deviceId}/videos`;
    const response = await fetch(url);

    if (!response.ok) {
      throw new Error(`Failed to list videos: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Get video details with all available versions
   */
  async getVideoDetails(videoId: string): Promise<VideoDetailsResponse> {
    if (!videoId) {
      throw new Error('videoId is required');
    }

    const url = `${this.processingEndpoint}/devices/${this.deviceId}/videos/${videoId}`;
    const response = await fetch(url);

    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Video not found');
      }
      throw new Error(`Failed to get video details: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Initiate video processing
   */
  async processVideo(videoId: string): Promise<ProcessVideoResponse> {
    if (!videoId) {
      throw new Error('videoId is required');
    }

    const url = `${this.processingEndpoint}/devices/${this.deviceId}/videos/${videoId}/process`;
    const response = await fetch(url, {
      method: 'POST',
    });

    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Video not found');
      }
      throw new Error(`Failed to process video: ${response.statusText}`);
    }

    return response.json();
  }

  /**
   * Get job status and progress
   */
  async getJobStatus(jobId: string): Promise<JobStatusResponse> {
    if (!jobId) {
      throw new Error('jobId is required');
    }

    const url = `${this.processingEndpoint}/jobs/${jobId}/status`;
    const response = await fetch(url);

    if (!response.ok) {
      if (response.status === 404) {
        throw new Error('Job not found');
      }
      throw new Error(`Failed to get job status: ${response.statusText}`);
    }

    return response.json();
  }
}

export const aiProcessing = new AIProcessingService();
