/**
 * Services
 * Central exports for all backend services
 * 
 * Generated by AGL
 */

export { DatabaseService, db } from './database.service';
export type { PrismaClient } from '@generated/prisma';

