/**
 * AIProcessingController * Business logic for aiprocessing feature
 * 
 * Generated by AGL
 */

// Domain types from spec
import { aiProcessing } from '@/services/aiprocessing.service';
import { DatabaseService } from '@/services/database.service';
import type { AIJob } from '@repo/types';

export class AIProcessingController {
  private aiProcessingService = aiProcessing;
  private db = DatabaseService.getInstance();

  /**
   * Controller methods for aiprocessing feature
   */

  /**
   * createAIJob   */
  async createAIJob(params: {
        videoId?: string;
        type?: string;
      }): Promise<any> {
    try {
      // Validate input
      if (!params.videoId) {
        throw new Error('videoId is required');
      }

      const type = params.type || 'summary';

      // Verify video exists in database
      const video = await this.db.video.findUnique({
        where: { id: params.videoId }
      });

      if (!video) {
        throw new Error(`Video with id ${params.videoId} not found`);
      }

      // Create AIJob record in database
      const aiJob = await this.db.aIJob.create({
        data: {
          videoId: params.videoId,
          type: type,
          status: 'pending',
        },
        include: {
          video: true,
        },
      });

      return {
        jobId: aiJob.id,
        videoId: aiJob.videoId,
        type: aiJob.type,
        status: aiJob.status,
        createdAt: aiJob.createdAt,
      };
    } catch (error) {
      console.error('Error in createAIJob:', error);
      throw error;
    }
  }

  /**
   * validateVideo - Validate that a video exists and is in correct format
   */
  async validateVideo(videoId: string): Promise<boolean> {
    try {
      // Validate input
      if (!videoId) {
        throw new Error('videoId is required');
      }

      // Attempt to get video details to validate it exists
      await this.aiProcessingService.getVideoDetails(videoId);

      return true;
    } catch (error) {
      console.error('Error in validateVideo:', error);
      throw error;
    }
  }

  /**
   * enqueueJob - Enqueue a video for processing
   */
  async enqueueJob(videoId: string): Promise<AIJob> {
    try {
      // Validate input
      if (!videoId) {
        throw new Error('videoId is required');
      }

      // Validate video exists
      await this.validateVideo(videoId);

      // Process the video
      const processResponse = await this.aiProcessingService.processVideo(videoId);

      // Create or update AIJob record in database
      const aiJob = await this.db.aIJob.upsert({
        where: { id: processResponse.data.jobId },
        update: {
          videoId: videoId,
        },
        create: {
          id: processResponse.data.jobId,
          videoId: videoId,
        },
        include: {
          video: true,
        },
      });

      return aiJob as AIJob;
    } catch (error) {
      console.error('Error in enqueueJob:', error);
      throw error;
    }
  }

  /**
   * listAIJobs   */
  async listAIJobs(): Promise<AIJob[]> {
    try {
      // Get all AI jobs from database
      const aiJobs = await this.db.aIJob.findMany({
        include: {
          video: true,
        },
      });

      return aiJobs as AIJob[];
    } catch (error) {
      console.error('Error in listAIJobs:', error);
      throw error;
    }
  }

  /**
   * getAIJob   */
  async getAIJob(params: {
        jobId?: string;
      }): Promise<AIJob> {
    try {
      // Validate input
      if (!params.jobId) {
        throw new Error('jobId is required');
      }

      // Get job from external processing service for status info
      const jobStatus = await this.aiProcessingService.getJobStatus(params.jobId);

      // Get job from database
      const aiJob = await this.db.aIJob.findUnique({
        where: { id: params.jobId },
        include: {
          video: true,
        },
      });

      if (!aiJob) {
        throw new Error('Job not found');
      }

      return aiJob as AIJob;
    } catch (error) {
      console.error('Error in getAIJob:', error);
      throw error;
    }
  }

  /**
   * listAIJobsByVideo   */
  async listAIJobsByVideo(params: {
        videoId?: string;
      }): Promise<AIJob[]> {
    try {
      // Validate input
      if (!params.videoId) {
        throw new Error('videoId is required');
      }

      // Validate video exists
      await this.validateVideo(params.videoId);

      // Get all AI jobs for this video from database
      const aiJobs = await this.db.aIJob.findMany({
        where: {
          videoId: params.videoId,
        },
        include: {
          video: true,
        },
      });

      return aiJobs as AIJob[];
    } catch (error) {
      console.error('Error in listAIJobsByVideo:', error);
      throw error;
    }
  }
}
