/**
 * Auto-generated entity types
 */

export interface AIJob {
  /** Primary key (auto-generated by database) */
  id: string;
  /** Created timestamp (auto-generated by database) */
  createdAt: Date | string;
  /** Updated timestamp (auto-generated by database) */
  updatedAt: Date | string;
}
