/**
 * Auto-generated entity types
 */
import type { Video } from '@repo/types';

export interface AIJob {
  /** Primary key (auto-generated by database) */
  id: string;
  video: Video;
  /** Created timestamp (auto-generated by database) */
  createdAt: Date | string;
  /** Updated timestamp (auto-generated by database) */
  updatedAt: Date | string;
}
