/**
 * Auto-generated entity types
 */

export interface Video {
  /** Primary key (auto-generated by database) */
  id: string;
  title: string;
  description: string;
  url: string;
  duration: number;
  userId: string;
  /** Created timestamp (auto-generated by database) */
  createdAt: Date | string;
  /** Updated timestamp (auto-generated by database) */
  updatedAt: Date | string;
}

export interface VideoListFilter {
  title: string;
  description: string;
  id: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  url: string;
  duration: number;
  userId: string;
}

export interface VideoCount {
  id: string;
  createdAt: Date | string;
  updatedAt: Date | string;
  title: string;
  description: string;
  url: string;
  duration: number;
  userId: string;
}

export interface VideoResponse {
  title: string;
  description: string;
  url: string;
  duration: number;
  aiResults: AIVideos;
}

export interface AIVideos {
  emoji: string;
  engaging: string;
  subtitles: string;
  original: string;
}
