/**
 * Auto-generated entity types
 */

export interface Video {
  /** Primary key (auto-generated by database) */
  id: string;
  title: string;
  description: string;
  url: string;
  duration: number;
  /** Created timestamp (auto-generated by database) */
  createdAt: Date | string;
  /** Updated timestamp (auto-generated by database) */
  updatedAt: Date | string;
}

export interface VideoListFilter {
  title: string;
  description: string;
}
